// Post List
export const LOAD_POST_LIST_REQUESTED = 'LOAD_POST_LIST_REQUESTED';
export const LOAD_POST_LIST_STARTED = 'LOAD_POST_LIST_STARTED';
export const LOAD_POST_LIST_SUCCESS = 'LOAD_POST_LIST_SUCCESS';
export const LOAD_POST_LIST_ERROR = 'LOAD_POST_LIST_ERROR';
